var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                     o                                                          ",
   "                          x                                                     ",
   "                              xx                   xx      xx    $              ",
   "                                             xx                  xx             ",
   "                                     $                           xxxxx          ",
   "                                   xxxxx                          vv     x   o  ",
   "                                                                            xx  ",
   "  xx                                                                         x  ",
   "  x                                       o o                           xx   x  ",
   "  x                                     xxxxxxx      xx                    o x  ",
   "  x           xx                                                           x x  ",
   "  x  @       x  x                                                            xP ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxx         xxxxxxxx     xxxxxxxxxxxxxxxxxx ",
   "                              x   x   x         x      x     x                  ",
   "                              x!!!x   x!!!!!!!!!x      x!!!!!x                  ",
   "                              x!!!x   x!!!!!!!!!x      x!!!!!x                  ",
   "                              xxxxx   xxxxxxxxxxx      xxxxxxx                  ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                        ",
   "                                                                                        ",
   "                                                                                        ",				   
   "          					        			    		                            ",		   
   " 																        		        ",	   
   "                       oo														        ",   
   "                    xxxxxxxx                                                 o          ",		   													   
   "                    x!!!!!!x                                        xxxxxxxxxx          ",   
   "                    x!!!!!!x   xxxxxxx  xxxxxxxxx      xxxxx                            ",		   
   "                    x!!!!!!x                                    P                       ",
   "                    x!!!!!!x                                  xxxxxx                    ",
   "                    x!!!!!!x                                                            ",	   
   "                     v    v                                     xxxxxxxx                ",
   "                                                                                        ", 																				   
   "x                                                     xxxxxxx                        x  ",
   "x                                                                                    x  ",                   
   "x                         o                                                          x  ",
   "x                      xxxxxxxxx                   xxxxxxx                           x  ",
   "x                                                                                    x  ",
   "x              xxxxx                                                                 x  ",                      
   "x                                           o                                        x  ",
   "x        xxxxx                            xxxxx                                      x  ",
   "x                                        xxxxxxx                                     x  ",
   "x                                        xxxxxxxx                                    x  ",
   "x  @                                     xxxxxxxxx                                   x  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   ",
   "                          x!!!!!!x                                                      "],
  ["                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",           
   "                                                                                             ",
   "                                                                                             ",
   "                                                                                             ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "   x                |     |     |    |     |     |     |     |     |     |                 x ",
   "   x                                                                                       x ",
   "   x                                                                                       x ",
   "   x                   o                  o               o     P     o                    x ",
   "   x          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x ",
   "   x =        x                  |                   |                                     x ", 
   "   x          x                                                                    xxxxxxxxx ",
   "   x         =x                                                                              ",
   "   x          x                                                                x             ",
   "   x   o  o   x                                                                              ",
   "   xxxxxxxxxxxx                                                                              ",
   "                                            xxxxxxx      xxxxxxx      xxxxxxxxxx             ",
   "                                                                                             ",
   "                              xxxxxxxx                                                       ",
   "                            x                                                                ",
   "                           xx                                                                ",
   "                        xxxxx                                                                ",
   "                  xxxxxxxxxxx                                                                ",
   "                                                                                             ",
   "                                                                                             ",
   "        xxxxxxx                                                                              ",
   "                                                                                             ",
   "  @                | o | o |                                                                 ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",      
   "                                                                                             "],
  ["                                                                                                              ",
   "																											  ",
   "																										      ",
   "																											  ",
   "                                                                                                              ",
   "																											  ",
   "																											  ",
   "                 																							  ",
   "                xx  xx   xxxxxx   xx    xx         xx           xx   xx  xxxx     xx   xx                     ",
   "                xx  xx   xx  xx   xx    xx         xx           xx       xx  x    xx   xx                     ",
   "                xxxxxx   xx  xx   xx    xx         xx    xxx    xx   xx  xx   x   xx   xx                     ",
   "                  xx     xx  xx   xx    xx         xx   x   x   xx   xx  xx    x  xx   xx                     ",
   "                  xx     xx  xx   xx    xx         xx  x     x  xx   xx  xx     x xx                          ",
   "                  xx     xxxxxx   xxxxxxxx         xxxx       xxxx   xx  xx      xxx   xx                     ",
   "                                                                                                              ",
   "                               																				  ",
   "																											  ",
   "																											  ",
   "																											  ",
   "					o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o					  ",
   " 																											  ",
   "					o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o					  ",
   "					                                                                         				  ",
   "	@				o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o	o					  ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
